Step 3: Implement API request, react router to enable back, and frame 2
Thayan/FreePark pull request #2
Opened 2023-08-21 19:53 UTC by Thayan

Integrate seach functionality in the UI (when user clicks search, make request to backend)

2023-08-22 14:01 UTC, AbdelrahmanRadwan requested changes

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/SearchResults.tsx
> +  }
e -> exception (use descriptive names).
After catching exception, it's important to log an error or warning.

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/SearchPage.tsx
> +    <>
It is a bad practice to have an empty tag. Could just be a span or div

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/ResultsTitle.tsx
> +    <div className="resultsTableHeader dark:text-gray-900 rtl:text-right">
this is a bad practice. Use separate css files to add the css configurations in. This comment applys on all of the other places too.

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/ResultsTable.tsx
> +                <Map />
What does this do actually?

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/ResultsTable.tsx
> +    const response = await getSearchResults("current location");
I think the method should return the state as well, that could be waiting/loading, success, or error, then you can check for error or loading and handle them differently.

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/ResultsTable.tsx
> +    if (!response) return;
Need to log something here.

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/ResultsPage.tsx
> +    <>
use div instead of empty tag.

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/ResultsPage.tsx
> +      <div className="mx-auto w-4/5">
separate css class.

2023-08-22 14:01 UTC, AbdelrahmanRadwan commented on src/Home.tsx
> +    this._roadSuffix = roadSuffix;
I don't even think that you need any of this. You just need a constructor and it will build the parking slot for you. You can map the API response into that constructor call directly.

2023-09-05 15:31 UTC, Thayan commented on src/ResultsTitle.tsx
> +    <div className="resultsTableHeader dark:text-gray-900 rtl:text-right">
Unfortunately when I make these changes it fails to compile

Failed to compile.

Syntax error: C:\Users\ThayanRaveendran\Documents\React Learning\FreePark\src\index.css The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive. (10:9)
   8 |     }
   9 |     .resultsTableHeader {
> 10 |         @apply py-3.5 px-4 text-sm font-normal text-left text-gray-500 dark: text-gray-400 rtl:text-right;
     |         ^
  11 |     }
  12 |     .resultsTableBody {
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError
Failed to compile.

Syntax error: C:\Users\ThayanRaveendran\Documents\React Learning\FreePark\src\index.css The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive. (10:9)
   8 |     }
   9 |     .resultsTableHeader {
> 10 |         @apply py-3.5 px-4 text-sm font-normal text-left text-gray-500 dark: text-gray-400 rtl:text-right dark: divide-gray-700;
     |         ^
  11 |     }
  12 |     .resultsTableBody {
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError
Failed to compile.

Syntax error: C:\Users\ThayanRaveendran\Documents\React Learning\FreePark\src\index.css The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive. (7:9)
  5 | @layer components {
  6 |     .resultsTable {
> 7 |         @apply mx-auto min-w-full divide-y divide-gray-200 dark: divide-gray-700;
    |         ^
  8 |     }
  9 |     .resultsTableHeader {
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError
Failed to compile.

Syntax error: C:\Users\ThayanRaveendran\Documents\React Learning\FreePark\src\index.css The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive. (7:9)
  5 | @layer components {
  6 |     .resultsTable {
> 7 |         @apply mx-auto min-w-full divide-y divide-gray-200 dark: divide-gray-700;
    |         ^
  8 |     }
  9 |     .resultsTableHeader {
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(7:9) C:\Users\ThayanRaveendran\Documents\React Learning\FreePark\src\index.css The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive.
Failed to compile.

Syntax error: C:\Users\ThayanRaveendran\Documents\React Learning\FreePark\src\index.css The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive. (7:9)
  5 | @layer components {
  6 |     .resultsTable {
> 7 |         @apply mx-auto min-w-full divide-y divide-gray-200 dark: divide-gray-700;
    |         ^
  8 |     }
  9 |     .resultsTableHeader {
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):

2023-09-05 15:32 UTC, Thayan commented on src/ResultsTable.tsx
> +                <Map />
It shows the map icon, I've renamed it to MapIcon for better clarification

2023-09-05 15:37 UTC, Thayan commented on src/ResultsTable.tsx
> +    if (!response) return;
Done

2023-09-05 15:39 UTC, Thayan commented on src/ResultsPage.tsx
> +    <>
Done

2023-09-05 15:45 UTC, Thayan commented on src/Home.tsx
> +    this._roadSuffix = roadSuffix;
I've made this change, but I needed to add ! to every param in the class - not sure if it's the right approach?

2023-09-05 15:48 UTC, Thayan commented on src/ResultsPage.tsx
> +      <div className="mx-auto w-4/5">
Caused a compile error when I made this change

2023-09-05 15:48 UTC, Thayan commented on src/SearchPage.tsx
> +    <>
Done

2023-09-05 15:48 UTC, Thayan commented on src/SearchResults.tsx
> +  }
Done

2023-09-05 15:50 UTC, merged